### ISSUE TITLE
Application Code

### ISSUE THREAD

**Issue by wolf943134497** [HKUST-Aerial-Robotics/G3Reg#2]
Hi @qiaozhijian  thanks for your great works!

Will the Multi-session Map Merging Application code be open source? 

How much better is G3Reg than methods like scancontext when do Map Merging Application?

Thanks

**Comment by qiaozhijian** [comment]
I'm sorry that the map merging code won't be open source because the code is the part of an unpublished work of my partner.

I didn't compare G3Reg with scancontext. But you can see the benchmark and video. The translation range of G3Reg is much larger than most loop closure methods which can only handle the translation below 5~10m.
