### ISSUE TITLE
Example of  Multi-session Map Merging

### ISSUE THREAD

**Issue by Tartisan** [HKUST-Aerial-Robotics/G3Reg#8]
Thanks for sharing your job ! Can you please provide the example data and config of `Multi-session Map Merging` ?

**Comment by qiaozhijian** [comment]
Thank you for your attention. Unfortunately, I cannot provide the code and data for multi-session SLAM because the code is the part of an unpublished work of my partner. It is important to note that this part is only used as an application for validating registration, and the technology used itself does not have any innovative points. When implementing this application, we referred to the work "[Kimera-Multi](https://arxiv.org/abs/2106.14386)". We hope this is helpful to you.
